### ISSUE TITLE
Compilation failure

### ISSUE THREAD

**Issue by fr0stbyte** [zombodb/pgx#73] opened 2021-01-12 03:28 UTC
```
cargo --version
cargo 1.49.0 (d00d64df9 2020-12-05)
```
```
cargo pgx --version
cargo-pgx 0.1.13
```

```
cargo pgx status
Postgres v10 is running
Postgres v11 is running
Postgres v12 is running
Postgres v13 is running
```
```
building extension with features `pg13`
"cargo" "build" "--features" "pg13" "--no-default-features"
   Compiling pgx v0.1.13 (/home/XXX/src/pgx/pgx)
error[E0603]: module `export` is private
   --> /home/XXX/src/pgx/pgx/src/list.rs:10:12
    |
10  | use serde::export::PhantomData;
    |            ^^^^^^ private module
    |
note: the module `export` is defined here
   --> /home/XXX/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.119/src/lib.rs:275:5
    |
275 | use self::__private as export;
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0392]: parameter `T` is never used
   --> /home/XXX/src/pgx/pgx/src/list.rs:216:30
    |
216 | struct PgListIteratorPtr<'a, T> {
    |                              ^ unused parameter
    |
    = help: consider removing `T`, referring to it in a field, or using a marker such as `PhantomData`

error[E0392]: parameter `T` is never used
   --> /home/XXX/src/pgx/pgx/src/list.rs:221:30
    |
221 | struct PgListIteratorOid<'a, T> {
    |                              ^ unused parameter
    |
    = help: consider removing `T`, referring to it in a field, or using a marker such as `PhantomData`

error[E0392]: parameter `T` is never used
   --> /home/XXX/src/pgx/pgx/src/list.rs:226:30
    |
226 | struct PgListIteratorInt<'a, T> {
    |                              ^ unused parameter
    |
    = help: consider removing `T`, referring to it in a field, or using a marker such as `PhantomData`

error: aborting due to 4 previous errors

Some errors have detailed explanations: E0392, E0603.
For more information about an error, try `rustc --explain E0392`.
error: could not compile `pgx`

To learn more, run the command again with --verbose.
     [error] failed to build extension
```

**Comment by fr0stbyte** [comment] 2021-01-12 03:34
I tried downgrading `cargo-pgx` to v0.1.{10,9,8} but they fail to install.

**Comment by eeeebbbbrrrr** [comment] 2021-01-12 03:35
Dang. This is the same as #71 but it’s been fixed as of 0.1.13.  WTH?

**Comment by fr0stbyte** [comment] 2021-01-12 03:39
forgot to mention, I tried to build one of the extensions in the `pgx-examples`

**Comment by eeeebbbbrrrr** [comment] 2021-01-12 03:40
which example amd what was your full cargo command?

Dealing with upstream dependencies is a gigantic PITA and I want to make that problem disappear for pgx.

**Comment by eeeebbbbrrrr** [comment] 2021-01-12 03:45
What happens if you run “cargo update” and then re-run your “cargo pgx” command?

**Comment by fr0stbyte** [comment] 2021-01-12 04:08
- I tried `arrays` and `bgworker`
- `cargo pgx run pg13` -- I tried pg10 too
- `cargo update && cargo pgx run pg13` yields the same result as before. btw it crashes the postgres server, so it needs to be restarted

**Comment by eeeebbbbrrrr** [comment] 2021-01-12 04:13
Now it sounds like we have two problems?  If things don’t compile how can we crash Postgres?

**Comment by fr0stbyte** [comment] 2021-01-12 04:25
No idea, but I noticed that after the compilation exits with error, if I run `cargo pgx status` the postgres version that was used is not running.
I see this in the logs
```
2021-01-11 23:07:05.554 EST [70287] LOG:  starting PostgreSQL 13.0 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 10.2.0, 64-bit
2021-01-11 23:07:05.554 EST [70287] LOG:  listening on IPv6 address "::1", port 28813
2021-01-11 23:07:05.554 EST [70287] LOG:  listening on IPv4 address "127.0.0.1", port 28813
2021-01-11 23:07:05.565 EST [70287] LOG:  listening on Unix socket "/home/XXX/.pgx/.s.PGSQL.28813"
2021-01-11 23:07:05.577 EST [70288] LOG:  database system was shut down at 2021-01-11 22:32:13 EST
2021-01-11 23:07:05.585 EST [70287] LOG:  database system is ready to accept connections
2021-01-11 23:07:08.975 EST [70287] LOG:  received fast shutdown request
2021-01-11 23:07:09.006 EST [70287] LOG:  aborting any active transactions
2021-01-11 23:07:09.006 EST [70287] LOG:  background worker "logical replication launcher" (PID 70294) exited with exit code 1
2021-01-11 23:07:09.006 EST [70289] LOG:  shutting down
2021-01-11 23:07:09.044 EST [70287] LOG:  database system is shut down
```

Btw, is this supposed to be ran under `nightly` toolchain or `stable` ?

**Comment by eeeebbbbrrrr** [comment] 2021-01-12 04:27
That not a crash. “cargo pgx” stops the target Postgres before it starts the compile. 

Also under “stable”.  We don’t track nightly. 

You confirmed you have cargo-pgx 0.1.13 installed.  Can you also confirm the git hash you have checked out for the examples?

**Comment by fr0stbyte** [comment] 2021-01-12 04:30
```
ommit 7db20163606b5b8b42c9b11aaaf7b50dd93f0db1 (HEAD -> master, tag: v0.1.13, origin/master, origin/HEAD)
Author: Eric B. Ridge <eebbrr@gmail.com>

    bump to v0.1.13
```

**Comment by eeeebbbbrrrr** [comment] 2021-01-12 04:34
I’m dumped right now. 

I’ll have to try and re-create this tomorrow from first-principles.

FWIW, I use pgx every day developing @zombodb and it works here.

any additional input or help you can provide is greatly appreciated.  Thanks for your engagement so far!

**Comment by fr0stbyte** [comment] 2021-01-12 04:34
Sure, let me know what other info you need me to provide.

**Comment by eeeebbbbrrrr** [comment] 2021-01-12 04:35
I have no idea.

maybe teach me how to use Cargo.lock correctly so this doesn’t happen again?  That was supposed to be the point of 0.1.13!

**Comment by eeeebbbbrrrr** [comment] 2021-01-12 04:36
The output of “cargo tree” might be interesting

**Comment by eeeebbbbrrrr** [comment] 2021-01-12 04:37
And a full re-create from installing cargo-pgx to checking out the fit repo to building those examples.  I realize I’m just asking you if your router is plugged in but I’m at a loss.

**Comment by fr0stbyte** [comment] 2021-01-12 17:05
```
pgx-parent v0.1.13 (/home/radu/src/pgx)
├── cargo-pgx v0.1.13 (/home/radu/src/pgx/cargo-pgx)
│   ├── clap v2.33.3
│   │   ├── ansi_term v0.11.0
│   │   ├── atty v0.2.14
│   │   │   └── libc v0.2.82
│   │   ├── bitflags v1.2.1
│   │   ├── strsim v0.8.0
│   │   ├── textwrap v0.11.0
│   │   │   └── unicode-width v0.1.8
│   │   ├── unicode-width v0.1.8
│   │   ├── vec_map v0.8.2
│   │   └── yaml-rust v0.3.5
│   ├── colored v2.0.0
│   │   ├── atty v0.2.14 (*)
│   │   └── lazy_static v1.4.0
│   ├── env_proxy v0.4.1
│   │   ├── log v0.4.11
│   │   │   └── cfg-if v0.1.10
│   │   └── url v2.2.0
│   │       ├── form_urlencoded v1.0.0
│   │       │   ├── matches v0.1.8
│   │       │   └── percent-encoding v2.1.0
│   │       ├── idna v0.2.0
│   │       │   ├── matches v0.1.8
│   │       │   ├── unicode-bidi v0.3.4
│   │       │   │   └── matches v0.1.8
│   │       │   └── unicode-normalization v0.1.16
│   │       │       └── tinyvec v1.1.0
│   │       │           └── tinyvec_macros v0.1.0
│   │       ├── matches v0.1.8
│   │       └── percent-encoding v2.1.0
│   ├── fork v0.1.18
│   │   └── libc v0.2.82
│   ├── num_cpus v1.13.0
│   │   └── libc v0.2.82
│   ├── pgx-utils v0.1.13 (/home/radu/src/pgx/pgx-utils)
│   │   ├── colored v2.0.0 (*)
│   │   ├── dirs v3.0.1
│   │   │   └── dirs-sys v0.3.5
│   │   │       └── libc v0.2.82
│   │   ├── proc-macro2 v1.0.24
│   │   │   └── unicode-xid v0.2.1
│   │   ├── quote v1.0.8
│   │   │   └── proc-macro2 v1.0.24 (*)
│   │   ├── regex v1.4.3
│   │   │   ├── aho-corasick v0.7.15
│   │   │   │   └── memchr v2.3.4
│   │   │   ├── memchr v2.3.4
│   │   │   ├── regex-syntax v0.6.22
│   │   │   └── thread_local v1.1.0
│   │   │       └── lazy_static v1.4.0
│   │   ├── serde v1.0.118
│   │   │   └── serde_derive v1.0.118 (proc-macro)
│   │   │       ├── proc-macro2 v1.0.24 (*)
│   │   │       ├── quote v1.0.8 (*)
│   │   │       └── syn v1.0.58
│   │   │           ├── proc-macro2 v1.0.24 (*)
│   │   │           ├── quote v1.0.8 (*)
│   │   │           └── unicode-xid v0.2.1
│   │   ├── serde_derive v1.0.118 (proc-macro) (*)
│   │   ├── syn v1.0.58 (*)
│   │   ├── toml v0.5.8
│   │   │   └── serde v1.0.118 (*)
│   │   ├── unescape v0.1.0
│   │   └── url v2.2.0 (*)
│   ├── proc-macro2 v1.0.24 (*)
│   ├── quote v1.0.8 (*)
│   ├── rayon v1.5.0
│   │   ├── crossbeam-deque v0.8.0
│   │   │   ├── cfg-if v1.0.0
│   │   │   ├── crossbeam-epoch v0.9.1
│   │   │   │   ├── cfg-if v1.0.0
│   │   │   │   ├── const_fn v0.4.5 (proc-macro)
│   │   │   │   ├── crossbeam-utils v0.8.1
│   │   │   │   │   ├── cfg-if v1.0.0
│   │   │   │   │   └── lazy_static v1.4.0
│   │   │   │   │   [build-dependencies]
│   │   │   │   │   └── autocfg v1.0.1
│   │   │   │   ├── lazy_static v1.4.0
│   │   │   │   ├── memoffset v0.6.1
│   │   │   │   │   [build-dependencies]
│   │   │   │   │   └── autocfg v1.0.1
│   │   │   │   └── scopeguard v1.1.0
│   │   │   └── crossbeam-utils v0.8.1 (*)
│   │   ├── either v1.6.1
│   │   └── rayon-core v1.9.0
│   │       ├── crossbeam-channel v0.5.0
│   │       │   ├── cfg-if v1.0.0
│   │       │   └── crossbeam-utils v0.8.1 (*)
│   │       ├── crossbeam-deque v0.8.0 (*)
│   │       ├── crossbeam-utils v0.8.1 (*)
│   │       ├── lazy_static v1.4.0
│   │       └── num_cpus v1.13.0 (*)
│   │   [build-dependencies]
│   │   └── autocfg v1.0.1
│   ├── regex v1.4.3 (*)
│   ├── rttp_client v0.1.0
│   │   ├── base64 v0.11.0
│   │   ├── flate2 v1.0.19
│   │   │   ├── cfg-if v1.0.0
│   │   │   ├── crc32fast v1.2.1
│   │   │   │   └── cfg-if v1.0.0
│   │   │   ├── libc v0.2.82
│   │   │   └── miniz_oxide v0.4.3
│   │   │       └── adler v0.2.3
│   │   │       [build-dependencies]
│   │   │       └── autocfg v1.0.1
│   │   ├── httpdate v0.3.2
│   │   ├── mime v0.3.16
│   │   ├── mime_guess v2.0.3
│   │   │   ├── mime v0.3.16
│   │   │   └── unicase v2.6.0
│   │   │       [build-dependencies]
│   │   │       └── version_check v0.9.2
│   │   │   [build-dependencies]
│   │   │   └── unicase v2.6.0 (*)
│   │   ├── native-tls v0.2.7
│   │   │   ├── log v0.4.11 (*)
│   │   │   ├── openssl v0.10.32
│   │   │   │   ├── bitflags v1.2.1
│   │   │   │   ├── cfg-if v1.0.0
│   │   │   │   ├── foreign-types v0.3.2
│   │   │   │   │   └── foreign-types-shared v0.1.1
│   │   │   │   ├── lazy_static v1.4.0
│   │   │   │   ├── libc v0.2.82
│   │   │   │   └── openssl-sys v0.9.60
│   │   │   │       └── libc v0.2.82
│   │   │   │       [build-dependencies]
│   │   │   │       ├── autocfg v1.0.1
│   │   │   │       ├── cc v1.0.66
│   │   │   │       └── pkg-config v0.3.19
│   │   │   ├── openssl-probe v0.1.2
│   │   │   └── openssl-sys v0.9.60 (*)
│   │   ├── percent-encoding v2.1.0
│   │   ├── rand v0.7.3
│   │   │   ├── getrandom v0.1.16
│   │   │   │   ├── cfg-if v1.0.0
│   │   │   │   └── libc v0.2.82
│   │   │   ├── libc v0.2.82
│   │   │   ├── rand_chacha v0.2.2
│   │   │   │   ├── ppv-lite86 v0.2.10
│   │   │   │   └── rand_core v0.5.1
│   │   │   │       └── getrandom v0.1.16 (*)
│   │   │   └── rand_core v0.5.1 (*)
│   │   ├── socks v0.3.3
│   │   │   ├── byteorder v1.4.2
│   │   │   └── libc v0.2.82
│   │   └── url v2.2.0 (*)
│   ├── syn v1.0.58 (*)
│   └── unescape v0.1.0
├── pgx v0.1.13 (/home/radu/src/pgx/pgx)
│   ├── atomic-traits v0.2.0
│   │   └── cfg-if v0.1.10
│   │   [build-dependencies]
│   │   └── rustc_version v0.2.3
│   │       └── semver v0.9.0
│   │           └── semver-parser v0.7.0
│   ├── bitflags v1.2.1
│   ├── enum-primitive-derive v0.2.1 (proc-macro)
│   │   ├── num-traits v0.2.14
│   │   │   [build-dependencies]
│   │   │   └── autocfg v1.0.1
│   │   ├── quote v1.0.8 (*)
│   │   └── syn v1.0.58 (*)
│   ├── hash32 v0.1.1
│   │   └── byteorder v1.4.2
│   ├── heapless v0.5.6
│   │   ├── as-slice v0.1.4
│   │   │   ├── generic-array v0.12.3
│   │   │   │   └── typenum v1.12.0
│   │   │   ├── generic-array v0.13.2
│   │   │   │   └── typenum v1.12.0
│   │   │   ├── generic-array v0.14.4
│   │   │   │   └── typenum v1.12.0
│   │   │   │   [build-dependencies]
│   │   │   │   └── version_check v0.9.2
│   │   │   └── stable_deref_trait v1.2.0
│   │   ├── generic-array v0.13.2 (*)
│   │   ├── hash32 v0.1.1 (*)
│   │   └── stable_deref_trait v1.2.0
│   ├── num-traits v0.2.14 (*)
│   ├── once_cell v1.5.2
│   ├── pgx-macros v0.1.13 (proc-macro) (/home/radu/src/pgx/pgx-macros)
│   │   ├── pgx-utils v0.1.13 (/home/radu/src/pgx/pgx-utils) (*)
│   │   ├── proc-macro2 v1.0.24 (*)
│   │   ├── quote v1.0.8 (*)
│   │   ├── syn v1.0.58 (*)
│   │   └── unescape v0.1.0
│   ├── pgx-pg-sys v0.1.13 (/home/radu/src/pgx/pgx-pg-sys)
│   │   ├── memoffset v0.6.1 (*)
│   │   ├── once_cell v1.5.2
│   │   └── pgx-macros v0.1.13 (proc-macro) (/home/radu/src/pgx/pgx-macros) (*)
│   │   [build-dependencies]
│   │   ├── bindgen v0.56.0
│   │   │   ├── bitflags v1.2.1
│   │   │   ├── cexpr v0.4.0
│   │   │   │   └── nom v5.1.2
│   │   │   │       └── memchr v2.3.4
│   │   │   │       [build-dependencies]
│   │   │   │       └── version_check v0.9.2
│   │   │   ├── clang-sys v1.0.3
│   │   │   │   ├── glob v0.3.0
│   │   │   │   ├── libc v0.2.82
│   │   │   │   └── libloading v0.6.6
│   │   │   │       └── cfg-if v1.0.0
│   │   │   │   [build-dependencies]
│   │   │   │   └── glob v0.3.0
│   │   │   ├── clap v2.33.3 (*)
│   │   │   ├── env_logger v0.8.2
│   │   │   │   ├── atty v0.2.14 (*)
│   │   │   │   ├── humantime v2.0.1
│   │   │   │   ├── log v0.4.11 (*)
│   │   │   │   ├── regex v1.4.3 (*)
│   │   │   │   └── termcolor v1.1.2
│   │   │   ├── lazy_static v1.4.0
│   │   │   ├── lazycell v1.3.0
│   │   │   ├── log v0.4.11 (*)
│   │   │   ├── peeking_take_while v0.1.2
│   │   │   ├── proc-macro2 v1.0.24 (*)
│   │   │   ├── quote v1.0.8 (*)
│   │   │   ├── regex v1.4.3 (*)
│   │   │   ├── rustc-hash v1.1.0
│   │   │   ├── shlex v0.1.1
│   │   │   └── which v3.1.1
│   │   │       └── libc v0.2.82
│   │   ├── build-deps v0.1.4
│   │   │   └── glob v0.3.0
│   │   ├── colored v2.0.0 (*)
│   │   ├── num_cpus v1.13.0 (*)
│   │   ├── pgx-utils v0.1.13 (/home/radu/src/pgx/pgx-utils) (*)
│   │   ├── proc-macro2 v1.0.24 (*)
│   │   ├── quote v1.0.8 (*)
│   │   ├── rayon v1.5.0 (*)
│   │   └── syn v1.0.58 (*)
│   ├── seahash v4.0.1
│   ├── serde v1.0.118 (*)
│   ├── serde_cbor v0.11.1
│   │   ├── half v1.6.0
│   │   └── serde v1.0.118 (*)
│   ├── serde_json v1.0.61
│   │   ├── itoa v0.4.7
│   │   ├── ryu v1.0.5
│   │   └── serde v1.0.118 (*)
│   ├── time v0.2.24
│   │   ├── const_fn v0.4.5 (proc-macro)
│   │   ├── libc v0.2.82
│   │   ├── standback v0.2.14
│   │   │   [build-dependencies]
│   │   │   └── version_check v0.9.2
│   │   └── time-macros v0.1.1
│   │       ├── proc-macro-hack v0.5.19 (proc-macro)
│   │       └── time-macros-impl v0.1.1 (proc-macro)
│   │           ├── proc-macro-hack v0.5.19 (proc-macro)
│   │           ├── proc-macro2 v1.0.24 (*)
│   │           ├── quote v1.0.8 (*)
│   │           ├── standback v0.2.14 (*)
│   │           └── syn v1.0.58 (*)
│   │   [build-dependencies]
│   │   └── version_check v0.9.2
│   └── uuid v0.8.1
│       └── rand v0.7.3 (*)
├── pgx-macros v0.1.13 (proc-macro) (/home/radu/src/pgx/pgx-macros) (*)
├── pgx-pg-sys v0.1.13 (/home/radu/src/pgx/pgx-pg-sys) (*)
└── pgx-tests v0.1.13 (/home/radu/src/pgx/pgx-tests)
    ├── colored v2.0.0 (*)
    ├── lazy_static v1.4.0
    ├── libc v0.2.82
    ├── pgx v0.1.13 (/home/radu/src/pgx/pgx) (*)
    ├── pgx-macros v0.1.13 (proc-macro) (/home/radu/src/pgx/pgx-macros) (*)
    ├── pgx-utils v0.1.13 (/home/radu/src/pgx/pgx-utils) (*)
    ├── postgres v0.19.0
    │   ├── bytes v1.0.0
    │   ├── fallible-iterator v0.2.0
    │   ├── futures v0.3.9
    │   │   ├── futures-channel v0.3.9
    │   │   │   ├── futures-core v0.3.9
    │   │   │   └── futures-sink v0.3.9
    │   │   ├── futures-core v0.3.9
    │   │   ├── futures-executor v0.3.9
    │   │   │   ├── futures-core v0.3.9
    │   │   │   ├── futures-task v0.3.9
    │   │   │   │   └── once_cell v1.5.2
    │   │   │   └── futures-util v0.3.9
    │   │   │       ├── futures-channel v0.3.9 (*)
    │   │   │       ├── futures-core v0.3.9
    │   │   │       ├── futures-io v0.3.9
    │   │   │       ├── futures-macro v0.3.9 (proc-macro)
    │   │   │       │   ├── proc-macro-hack v0.5.19 (proc-macro)
    │   │   │       │   ├── proc-macro2 v1.0.24 (*)
    │   │   │       │   ├── quote v1.0.8 (*)
    │   │   │       │   └── syn v1.0.58 (*)
    │   │   │       ├── futures-sink v0.3.9
    │   │   │       ├── futures-task v0.3.9 (*)
    │   │   │       ├── memchr v2.3.4
    │   │   │       ├── pin-project-lite v0.2.1
    │   │   │       ├── pin-utils v0.1.0
    │   │   │       ├── proc-macro-hack v0.5.19 (proc-macro)
    │   │   │       ├── proc-macro-nested v0.1.6
    │   │   │       └── slab v0.4.2
    │   │   ├── futures-io v0.3.9
    │   │   ├── futures-sink v0.3.9
    │   │   ├── futures-task v0.3.9 (*)
    │   │   └── futures-util v0.3.9 (*)
    │   ├── log v0.4.11 (*)
    │   ├── tokio v1.0.1
    │   │   ├── bytes v1.0.0
    │   │   ├── libc v0.2.82
    │   │   ├── memchr v2.3.4
    │   │   ├── mio v0.7.7
    │   │   │   ├── libc v0.2.82
    │   │   │   └── log v0.4.11 (*)
    │   │   └── pin-project-lite v0.2.1
    │   │   [build-dependencies]
    │   │   └── autocfg v1.0.1
    │   └── tokio-postgres v0.7.0
    │       ├── async-trait v0.1.42 (proc-macro)
    │       │   ├── proc-macro2 v1.0.24 (*)
    │       │   ├── quote v1.0.8 (*)
    │       │   └── syn v1.0.58 (*)
    │       ├── byteorder v1.4.2
    │       ├── bytes v1.0.0
    │       ├── fallible-iterator v0.2.0
    │       ├── futures v0.3.9 (*)
    │       ├── log v0.4.11 (*)
    │       ├── parking_lot v0.11.1
    │       │   ├── instant v0.1.9
    │       │   │   └── cfg-if v1.0.0
    │       │   ├── lock_api v0.4.2
    │       │   │   └── scopeguard v1.1.0
    │       │   └── parking_lot_core v0.8.2
    │       │       ├── cfg-if v1.0.0
    │       │       ├── instant v0.1.9 (*)
    │       │       ├── libc v0.2.82
    │       │       └── smallvec v1.6.1
    │       ├── percent-encoding v2.1.0
    │       ├── phf v0.8.0
    │       │   └── phf_shared v0.8.0
    │       │       └── siphasher v0.3.3
    │       ├── pin-project-lite v0.2.1
    │       ├── postgres-protocol v0.6.0
    │       │   ├── base64 v0.13.0
    │       │   ├── byteorder v1.4.2
    │       │   ├── bytes v1.0.0
    │       │   ├── fallible-iterator v0.2.0
    │       │   ├── hmac v0.10.1
    │       │   │   ├── crypto-mac v0.10.0
    │       │   │   │   ├── generic-array v0.14.4 (*)
    │       │   │   │   └── subtle v2.4.0
    │       │   │   └── digest v0.9.0
    │       │   │       └── generic-array v0.14.4 (*)
    │       │   ├── md5 v0.7.0
    │       │   ├── memchr v2.3.4
    │       │   ├── rand v0.8.1
    │       │   │   ├── libc v0.2.82
    │       │   │   ├── rand_chacha v0.3.0
    │       │   │   │   ├── ppv-lite86 v0.2.10
    │       │   │   │   └── rand_core v0.6.1
    │       │   │   │       └── getrandom v0.2.1
    │       │   │   │           ├── cfg-if v1.0.0
    │       │   │   │           └── libc v0.2.82
    │       │   │   └── rand_core v0.6.1 (*)
    │       │   ├── sha2 v0.9.2
    │       │   │   ├── block-buffer v0.9.0
    │       │   │   │   └── generic-array v0.14.4 (*)
    │       │   │   ├── cfg-if v1.0.0
    │       │   │   ├── cpuid-bool v0.1.2
    │       │   │   ├── digest v0.9.0 (*)
    │       │   │   └── opaque-debug v0.3.0
    │       │   └── stringprep v0.1.2
    │       │       ├── unicode-bidi v0.3.4 (*)
    │       │       └── unicode-normalization v0.1.16 (*)
    │       ├── postgres-types v0.2.0
    │       │   ├── bytes v1.0.0
    │       │   ├── fallible-iterator v0.2.0
    │       │   └── postgres-protocol v0.6.0 (*)
    │       ├── socket2 v0.3.19
    │       │   ├── cfg-if v1.0.0
    │       │   └── libc v0.2.82
    │       ├── tokio v1.0.1 (*)
    │       └── tokio-util v0.6.0
    │           ├── bytes v1.0.0
    │           ├── futures-core v0.3.9
    │           ├── futures-sink v0.3.9
    │           ├── log v0.4.11 (*)
    │           ├── pin-project-lite v0.2.1
    │           ├── tokio v1.0.1 (*)
    │           └── tokio-stream v0.1.1
    │               ├── futures-core v0.3.9
    │               ├── pin-project-lite v0.2.1
    │               └── tokio v1.0.1 (*)
    ├── regex v1.4.3 (*)
    ├── serde v1.0.118 (*)
    ├── serde_json v1.0.61 (*)
    ├── shutdown_hooks v0.1.0
    └── time v0.2.24 (*)
```

**Comment by eeeebbbbrrrr** [comment] 2021-01-12 17:08
I'm seeing this  now on GitHub Action tests for both pgx and ZomboDB.  

How do you make a per-crate `Cargo.lock` when the overall project structure is workspace-based?  Can I just run `cargo generate-lockfile` in each workspace crate and it'll magically work?  The cargo docs kinda say that if you have a workspace project you only need (want?) one `Cargo.lock` on the top-level.  

But how do you handle `Cargo.lock` when subcrates are published to crates.io individually?

**Comment by fr0stbyte** [comment] 2021-01-12 18:00
from the docs, it seems that if one's using workspaces there is a single Cargo.lock at the root level used by inner crates
https://doc.rust-lang.org/cargo/reference/workspaces.html

> All packages share a common Cargo.lock file which resides in the workspace root.

**Comment by eeeebbbbrrrr** [comment] 2021-01-12 18:05
That's how I read it too, but it doesn't seem to be the case when publishing to crates.io.  I'm not really sure, but if that's how it worked then I don't think we'd be running into this problem.  

Which looks like serde changed something.  I'm trying to re-create this locally <short pause>... and it seems I can after doing a "cargo update".

**Comment by eeeebbbbrrrr** [comment] 2021-01-12 18:09
Okay, I got the compilation problem.  Looks like I accidentally imported serde's `PhantomData` type when I meant to import `std::marker::PhantomData`.

And perhaps where I messed up with `Cargo.lock` was that I wasn't locally updated via `cargo update`.  I'll adjust my little scripts to do this for me automatically.

**Comment by eeeebbbbrrrr** [comment] 2021-01-12 18:14
Okay, I'll have 0.1.14 released in a little bit.  I want to wait for GH Actions to be green first.

**Comment by eeeebbbbrrrr** [comment] 2021-01-12 19:23
alrighty, 0.1.14 is published.  Thanks for the report and your participation @fr0stbyte!

**Closed by eeeebbbbrrrr** 2021-01-12 19:23 UTC

**Comment by fr0stbyte** [comment] 2021-01-12 20:27
confirmed this passes compilation. Thanks for the swift fix.
